services:
  backend:
    image: houtaru0709/mern-backend:1.0
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: $"mongodb+srv://thuansad001_db_user:hou_0709@cloud-lab.udgdfhq.mongodb.net/cloud-lab?appName=cloud-lab"

  frontend:
    image: houtaru0709/mern-frontend:2.0
    ports:
      - "3000:3000"
    depends_on:
      - backend